language: ruby
exclude: [vendor]
rvm:
- 2.3.3
script: "bundle install & bundle exec jekyll build"

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local_dir: _site
  target-branch: master
  github-token: $GH_TOKEN 
  committer-from-gh: true 
  on:
    branch: src

notifications:
  email: false

branches:
  only:
  - src

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
